;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua--prefix-override-handler
        electric-newline-and-maybe-indent
        helm-M-x
        ignore
        indent-for-tab-command
        lsp-ui-doc--handle-mouse-movement
        mouse-set-region
        slim-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        cua-copy-region
        cua-paste
        keyboard-escape-quit
        lsp-mouse-click
        projectile-find-file
        ))
